### ISSUE TITLE
Alexa App Complains: "Unable to link XXX at this time"

### ISSUE THREAD

**Issue by mingdee** [alexa-samples/alexa-oauth-sample#5]
The oauth sample creation in aws using CloudFormation works. During the account linking in the Alexa app, the user login seems fine too. But after the "Authorize" button is clicked, the app returns and shows "We were unable to link TruSens at this time". Checked the OAuthCode table and each time there is a new authorization code generated. Any idea what goes wrong? 
![IMG_2C933E95795C-1](https://user-images.githubusercontent.com/351278/77701233-33992300-6f8c-11ea-9bc6-f02e37f0a5ab.jpeg)

**Comment by jonenet** [comment]
Did you solve the problem?

**Comment by sssjjf** [comment]
Perhaps you can check to see if your server receives acceptGrant requests. If not, you can check to see if your browser blocks your url

**Comment by aszk** [comment]
Please feel free to contact us if your issue still persists. https://alexa.design/contactus
